### ISSUE TITLE
Missing  `PM_functions/PM_files/30_250galactic.mat` ?

### ISSUE THREAD

**Issue by niess** [grand-mother/data_challenge1_pm_lwp#2]
Hello,

and happy new year :)

Concerning the PM pipeline, I've got the following error when running in external mode as

```
> rm -rf results && time ./efield2adc_alltraces_external_pipeline.py data/Coarse2_xmax_add.root -p PM_pipeline.yaml -od results
************** Analysing file data/Coarse2_xmax_add.root
...
Applying  generate_galacticnoise
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'PM_functions/PM_files/30_250galactic.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

The file `30_250galactic.mat` is indeed missing. I downloaded PM_files from the link in the `README.md`.

Note that if I comment out the galactic noise part in `PM_pipeline.yaml`, then the pipeline seems to run properly :)

**Comment by niess** [comment]
Now I just found the missing file in the XDU tarball. I guess that the same is used in both pipelines?

**Comment by lwpiotr** [comment]
Sorry for noticing this issue so late - I must have not set up properly email modifications. Yes, the file is the same, but I should have included it in the PM tarball. My bad.

**Comment by lwpiotr** [comment]
Updated the tar.gz file and the link in the readme.

**Comment by niess** [comment]
Great. Thank you :+1:
